// Code generated by go-swagger; DO NOT EDIT.

package leagues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLeaguesParams creates a new GetLeaguesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLeaguesParams() *GetLeaguesParams {
	return &GetLeaguesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLeaguesParamsWithTimeout creates a new GetLeaguesParams object
// with the ability to set a timeout on a request.
func NewGetLeaguesParamsWithTimeout(timeout time.Duration) *GetLeaguesParams {
	return &GetLeaguesParams{
		timeout: timeout,
	}
}

// NewGetLeaguesParamsWithContext creates a new GetLeaguesParams object
// with the ability to set a context for a request.
func NewGetLeaguesParamsWithContext(ctx context.Context) *GetLeaguesParams {
	return &GetLeaguesParams{
		Context: ctx,
	}
}

// NewGetLeaguesParamsWithHTTPClient creates a new GetLeaguesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLeaguesParamsWithHTTPClient(client *http.Client) *GetLeaguesParams {
	return &GetLeaguesParams{
		HTTPClient: client,
	}
}

/* GetLeaguesParams contains all the parameters to send to the API endpoint
   for the get leagues operation.

   Typically these are written to a http.Request.
*/
type GetLeaguesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get leagues params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLeaguesParams) WithDefaults() *GetLeaguesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get leagues params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLeaguesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get leagues params
func (o *GetLeaguesParams) WithTimeout(timeout time.Duration) *GetLeaguesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get leagues params
func (o *GetLeaguesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get leagues params
func (o *GetLeaguesParams) WithContext(ctx context.Context) *GetLeaguesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get leagues params
func (o *GetLeaguesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get leagues params
func (o *GetLeaguesParams) WithHTTPClient(client *http.Client) *GetLeaguesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get leagues params
func (o *GetLeaguesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLeaguesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
