// Code generated by go-swagger; DO NOT EDIT.

package leagues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetLeaguesLeagueIDMatchesParams creates a new GetLeaguesLeagueIDMatchesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLeaguesLeagueIDMatchesParams() *GetLeaguesLeagueIDMatchesParams {
	return &GetLeaguesLeagueIDMatchesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLeaguesLeagueIDMatchesParamsWithTimeout creates a new GetLeaguesLeagueIDMatchesParams object
// with the ability to set a timeout on a request.
func NewGetLeaguesLeagueIDMatchesParamsWithTimeout(timeout time.Duration) *GetLeaguesLeagueIDMatchesParams {
	return &GetLeaguesLeagueIDMatchesParams{
		timeout: timeout,
	}
}

// NewGetLeaguesLeagueIDMatchesParamsWithContext creates a new GetLeaguesLeagueIDMatchesParams object
// with the ability to set a context for a request.
func NewGetLeaguesLeagueIDMatchesParamsWithContext(ctx context.Context) *GetLeaguesLeagueIDMatchesParams {
	return &GetLeaguesLeagueIDMatchesParams{
		Context: ctx,
	}
}

// NewGetLeaguesLeagueIDMatchesParamsWithHTTPClient creates a new GetLeaguesLeagueIDMatchesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLeaguesLeagueIDMatchesParamsWithHTTPClient(client *http.Client) *GetLeaguesLeagueIDMatchesParams {
	return &GetLeaguesLeagueIDMatchesParams{
		HTTPClient: client,
	}
}

/* GetLeaguesLeagueIDMatchesParams contains all the parameters to send to the API endpoint
   for the get leagues league ID matches operation.

   Typically these are written to a http.Request.
*/
type GetLeaguesLeagueIDMatchesParams struct {

	/* LeagueID.

	   League ID
	*/
	LeagueID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get leagues league ID matches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLeaguesLeagueIDMatchesParams) WithDefaults() *GetLeaguesLeagueIDMatchesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get leagues league ID matches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLeaguesLeagueIDMatchesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) WithTimeout(timeout time.Duration) *GetLeaguesLeagueIDMatchesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) WithContext(ctx context.Context) *GetLeaguesLeagueIDMatchesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) WithHTTPClient(client *http.Client) *GetLeaguesLeagueIDMatchesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLeagueID adds the leagueID to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) WithLeagueID(leagueID int64) *GetLeaguesLeagueIDMatchesParams {
	o.SetLeagueID(leagueID)
	return o
}

// SetLeagueID adds the leagueId to the get leagues league ID matches params
func (o *GetLeaguesLeagueIDMatchesParams) SetLeagueID(leagueID int64) {
	o.LeagueID = leagueID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLeaguesLeagueIDMatchesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param league_id
	if err := r.SetPathParam("league_id", swag.FormatInt64(o.LeagueID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
