// Code generated by go-swagger; DO NOT EDIT.

package leagues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new leagues API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for leagues API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetLeagues(params *GetLeaguesParams, opts ...ClientOption) (*GetLeaguesOK, error)

	GetLeaguesLeagueID(params *GetLeaguesLeagueIDParams, opts ...ClientOption) (*GetLeaguesLeagueIDOK, error)

	GetLeaguesLeagueIDMatches(params *GetLeaguesLeagueIDMatchesParams, opts ...ClientOption) (*GetLeaguesLeagueIDMatchesOK, error)

	GetLeaguesLeagueIDTeams(params *GetLeaguesLeagueIDTeamsParams, opts ...ClientOption) (*GetLeaguesLeagueIDTeamsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetLeagues gs e t leagues

  Get league data
*/
func (a *Client) GetLeagues(params *GetLeaguesParams, opts ...ClientOption) (*GetLeaguesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLeaguesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetLeagues",
		Method:             "GET",
		PathPattern:        "/leagues",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLeaguesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLeaguesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetLeagues: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetLeaguesLeagueID gs e t leagues league id

  Get data for a league
*/
func (a *Client) GetLeaguesLeagueID(params *GetLeaguesLeagueIDParams, opts ...ClientOption) (*GetLeaguesLeagueIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLeaguesLeagueIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetLeaguesLeagueID",
		Method:             "GET",
		PathPattern:        "/leagues/{league_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLeaguesLeagueIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLeaguesLeagueIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetLeaguesLeagueID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetLeaguesLeagueIDMatches gs e t leagues league id matches

  Get matches for a team
*/
func (a *Client) GetLeaguesLeagueIDMatches(params *GetLeaguesLeagueIDMatchesParams, opts ...ClientOption) (*GetLeaguesLeagueIDMatchesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLeaguesLeagueIDMatchesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetLeaguesLeagueIDMatches",
		Method:             "GET",
		PathPattern:        "/leagues/{league_id}/matches",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLeaguesLeagueIDMatchesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLeaguesLeagueIDMatchesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetLeaguesLeagueIDMatches: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetLeaguesLeagueIDTeams gs e t leagues league id teams

  Get teams for a league
*/
func (a *Client) GetLeaguesLeagueIDTeams(params *GetLeaguesLeagueIDTeamsParams, opts ...ClientOption) (*GetLeaguesLeagueIDTeamsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLeaguesLeagueIDTeamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetLeaguesLeagueIDTeams",
		Method:             "GET",
		PathPattern:        "/leagues/{league_id}/teams",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLeaguesLeagueIDTeamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLeaguesLeagueIDTeamsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetLeaguesLeagueIDTeams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
