// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"27n/client/benchmarks"
	"27n/client/constants"
	"27n/client/distributions"
	"27n/client/explorer"
	"27n/client/find_matches"
	"27n/client/health"
	"27n/client/hero_stats"
	"27n/client/heroes"
	"27n/client/leagues"
	"27n/client/live"
	"27n/client/matches"
	"27n/client/metadata"
	"27n/client/parsed_matches"
	"27n/client/players_by_rank"
	"27n/client/pro_matches"
	"27n/client/pro_players"
	"27n/client/public_matches"
	"27n/client/rankings"
	"27n/client/records"
	"27n/client/replays"
	"27n/client/request"
	"27n/client/scenarios"
	"27n/client/schema"
	"27n/client/search"
	"27n/client/status"
	"27n/client/teams"
)

// Default nr27n API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.opendota.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new nr27n API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Nr27nAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new nr27n API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Nr27nAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new nr27n API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Nr27nAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Nr27nAPI)
	cli.Transport = transport
	cli.Benchmarks = benchmarks.New(transport, formats)
	cli.Constants = constants.New(transport, formats)
	cli.Distributions = distributions.New(transport, formats)
	cli.Explorer = explorer.New(transport, formats)
	cli.FindMatches = find_matches.New(transport, formats)
	cli.Health = health.New(transport, formats)
	cli.HeroStats = hero_stats.New(transport, formats)
	cli.Heroes = heroes.New(transport, formats)
	cli.Leagues = leagues.New(transport, formats)
	cli.Live = live.New(transport, formats)
	cli.Matches = matches.New(transport, formats)
	cli.Metadata = metadata.New(transport, formats)
	cli.ParsedMatches = parsed_matches.New(transport, formats)
	cli.PlayersByRank = players_by_rank.New(transport, formats)
	cli.ProMatches = pro_matches.New(transport, formats)
	cli.ProPlayers = pro_players.New(transport, formats)
	cli.PublicMatches = public_matches.New(transport, formats)
	cli.Rankings = rankings.New(transport, formats)
	cli.Records = records.New(transport, formats)
	cli.Replays = replays.New(transport, formats)
	cli.Request = request.New(transport, formats)
	cli.Scenarios = scenarios.New(transport, formats)
	cli.Schema = schema.New(transport, formats)
	cli.Search = search.New(transport, formats)
	cli.Status = status.New(transport, formats)
	cli.Teams = teams.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Nr27nAPI is a client for nr27n API
type Nr27nAPI struct {
	Benchmarks benchmarks.ClientService

	Constants constants.ClientService

	Distributions distributions.ClientService

	Explorer explorer.ClientService

	FindMatches find_matches.ClientService

	Health health.ClientService

	HeroStats hero_stats.ClientService

	Heroes heroes.ClientService

	Leagues leagues.ClientService

	Live live.ClientService

	Matches matches.ClientService

	Metadata metadata.ClientService

	ParsedMatches parsed_matches.ClientService

	PlayersByRank players_by_rank.ClientService

	ProMatches pro_matches.ClientService

	ProPlayers pro_players.ClientService

	PublicMatches public_matches.ClientService

	Rankings rankings.ClientService

	Records records.ClientService

	Replays replays.ClientService

	Request request.ClientService

	Scenarios scenarios.ClientService

	Schema schema.ClientService

	Search search.ClientService

	Status status.ClientService

	Teams teams.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Nr27nAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Benchmarks.SetTransport(transport)
	c.Constants.SetTransport(transport)
	c.Distributions.SetTransport(transport)
	c.Explorer.SetTransport(transport)
	c.FindMatches.SetTransport(transport)
	c.Health.SetTransport(transport)
	c.HeroStats.SetTransport(transport)
	c.Heroes.SetTransport(transport)
	c.Leagues.SetTransport(transport)
	c.Live.SetTransport(transport)
	c.Matches.SetTransport(transport)
	c.Metadata.SetTransport(transport)
	c.ParsedMatches.SetTransport(transport)
	c.PlayersByRank.SetTransport(transport)
	c.ProMatches.SetTransport(transport)
	c.ProPlayers.SetTransport(transport)
	c.PublicMatches.SetTransport(transport)
	c.Rankings.SetTransport(transport)
	c.Records.SetTransport(transport)
	c.Replays.SetTransport(transport)
	c.Request.SetTransport(transport)
	c.Scenarios.SetTransport(transport)
	c.Schema.SetTransport(transport)
	c.Search.SetTransport(transport)
	c.Status.SetTransport(transport)
	c.Teams.SetTransport(transport)
}
