// Code generated by go-swagger; DO NOT EDIT.

package heroes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetHeroesReader is a Reader for the GetHeroes structure.
type GetHeroesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHeroesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHeroesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHeroesOK creates a GetHeroesOK with default headers values
func NewGetHeroesOK() *GetHeroesOK {
	return &GetHeroesOK{}
}

/* GetHeroesOK describes a response with status code 200, with default header values.

Success
*/
type GetHeroesOK struct {
	Payload []*GetHeroesOKBodyItems0
}

func (o *GetHeroesOK) Error() string {
	return fmt.Sprintf("[GET /heroes][%d] getHeroesOK  %+v", 200, o.Payload)
}
func (o *GetHeroesOK) GetPayload() []*GetHeroesOKBodyItems0 {
	return o.Payload
}

func (o *GetHeroesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetHeroesOKBodyItems0 get heroes o k body items0
swagger:model GetHeroesOKBodyItems0
*/
type GetHeroesOKBodyItems0 struct {

	// Hero attack type, either 'Melee' or 'Ranged'
	AttackType string `json:"attack_type,omitempty"`

	// Numeric identifier for the hero object
	ID int64 `json:"id,omitempty"`

	// Hero name, e.g. 'Anti-Mage'
	LocalizedName string `json:"localized_name,omitempty"`

	// Dota hero command name, e.g. 'npc_dota_hero_antimage'
	Name string `json:"name,omitempty"`

	// Hero primary shorthand attribute name, e.g. 'agi'
	PrimaryAttr string `json:"primary_attr,omitempty"`

	// roles
	Roles []string `json:"roles"`
}

// Validate validates this get heroes o k body items0
func (o *GetHeroesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get heroes o k body items0 based on context it is used
func (o *GetHeroesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetHeroesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
