// Code generated by go-swagger; DO NOT EDIT.

package heroes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHeroesParams creates a new GetHeroesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHeroesParams() *GetHeroesParams {
	return &GetHeroesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeroesParamsWithTimeout creates a new GetHeroesParams object
// with the ability to set a timeout on a request.
func NewGetHeroesParamsWithTimeout(timeout time.Duration) *GetHeroesParams {
	return &GetHeroesParams{
		timeout: timeout,
	}
}

// NewGetHeroesParamsWithContext creates a new GetHeroesParams object
// with the ability to set a context for a request.
func NewGetHeroesParamsWithContext(ctx context.Context) *GetHeroesParams {
	return &GetHeroesParams{
		Context: ctx,
	}
}

// NewGetHeroesParamsWithHTTPClient creates a new GetHeroesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHeroesParamsWithHTTPClient(client *http.Client) *GetHeroesParams {
	return &GetHeroesParams{
		HTTPClient: client,
	}
}

/* GetHeroesParams contains all the parameters to send to the API endpoint
   for the get heroes operation.

   Typically these are written to a http.Request.
*/
type GetHeroesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get heroes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesParams) WithDefaults() *GetHeroesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get heroes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get heroes params
func (o *GetHeroesParams) WithTimeout(timeout time.Duration) *GetHeroesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get heroes params
func (o *GetHeroesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get heroes params
func (o *GetHeroesParams) WithContext(ctx context.Context) *GetHeroesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get heroes params
func (o *GetHeroesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get heroes params
func (o *GetHeroesParams) WithHTTPClient(client *http.Client) *GetHeroesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get heroes params
func (o *GetHeroesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeroesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
