// Code generated by go-swagger; DO NOT EDIT.

package heroes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetHeroesHeroIDMatchupsParams creates a new GetHeroesHeroIDMatchupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHeroesHeroIDMatchupsParams() *GetHeroesHeroIDMatchupsParams {
	return &GetHeroesHeroIDMatchupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeroesHeroIDMatchupsParamsWithTimeout creates a new GetHeroesHeroIDMatchupsParams object
// with the ability to set a timeout on a request.
func NewGetHeroesHeroIDMatchupsParamsWithTimeout(timeout time.Duration) *GetHeroesHeroIDMatchupsParams {
	return &GetHeroesHeroIDMatchupsParams{
		timeout: timeout,
	}
}

// NewGetHeroesHeroIDMatchupsParamsWithContext creates a new GetHeroesHeroIDMatchupsParams object
// with the ability to set a context for a request.
func NewGetHeroesHeroIDMatchupsParamsWithContext(ctx context.Context) *GetHeroesHeroIDMatchupsParams {
	return &GetHeroesHeroIDMatchupsParams{
		Context: ctx,
	}
}

// NewGetHeroesHeroIDMatchupsParamsWithHTTPClient creates a new GetHeroesHeroIDMatchupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHeroesHeroIDMatchupsParamsWithHTTPClient(client *http.Client) *GetHeroesHeroIDMatchupsParams {
	return &GetHeroesHeroIDMatchupsParams{
		HTTPClient: client,
	}
}

/* GetHeroesHeroIDMatchupsParams contains all the parameters to send to the API endpoint
   for the get heroes hero ID matchups operation.

   Typically these are written to a http.Request.
*/
type GetHeroesHeroIDMatchupsParams struct {

	/* HeroID.

	   Hero ID
	*/
	HeroID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get heroes hero ID matchups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesHeroIDMatchupsParams) WithDefaults() *GetHeroesHeroIDMatchupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get heroes hero ID matchups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesHeroIDMatchupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) WithTimeout(timeout time.Duration) *GetHeroesHeroIDMatchupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) WithContext(ctx context.Context) *GetHeroesHeroIDMatchupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) WithHTTPClient(client *http.Client) *GetHeroesHeroIDMatchupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeroID adds the heroID to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) WithHeroID(heroID int64) *GetHeroesHeroIDMatchupsParams {
	o.SetHeroID(heroID)
	return o
}

// SetHeroID adds the heroId to the get heroes hero ID matchups params
func (o *GetHeroesHeroIDMatchupsParams) SetHeroID(heroID int64) {
	o.HeroID = heroID
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeroesHeroIDMatchupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hero_id
	if err := r.SetPathParam("hero_id", swag.FormatInt64(o.HeroID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
