// Code generated by go-swagger; DO NOT EDIT.

package heroes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetHeroesHeroIDItemPopularityParams creates a new GetHeroesHeroIDItemPopularityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHeroesHeroIDItemPopularityParams() *GetHeroesHeroIDItemPopularityParams {
	return &GetHeroesHeroIDItemPopularityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeroesHeroIDItemPopularityParamsWithTimeout creates a new GetHeroesHeroIDItemPopularityParams object
// with the ability to set a timeout on a request.
func NewGetHeroesHeroIDItemPopularityParamsWithTimeout(timeout time.Duration) *GetHeroesHeroIDItemPopularityParams {
	return &GetHeroesHeroIDItemPopularityParams{
		timeout: timeout,
	}
}

// NewGetHeroesHeroIDItemPopularityParamsWithContext creates a new GetHeroesHeroIDItemPopularityParams object
// with the ability to set a context for a request.
func NewGetHeroesHeroIDItemPopularityParamsWithContext(ctx context.Context) *GetHeroesHeroIDItemPopularityParams {
	return &GetHeroesHeroIDItemPopularityParams{
		Context: ctx,
	}
}

// NewGetHeroesHeroIDItemPopularityParamsWithHTTPClient creates a new GetHeroesHeroIDItemPopularityParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHeroesHeroIDItemPopularityParamsWithHTTPClient(client *http.Client) *GetHeroesHeroIDItemPopularityParams {
	return &GetHeroesHeroIDItemPopularityParams{
		HTTPClient: client,
	}
}

/* GetHeroesHeroIDItemPopularityParams contains all the parameters to send to the API endpoint
   for the get heroes hero ID item popularity operation.

   Typically these are written to a http.Request.
*/
type GetHeroesHeroIDItemPopularityParams struct {

	/* HeroID.

	   Hero ID
	*/
	HeroID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get heroes hero ID item popularity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesHeroIDItemPopularityParams) WithDefaults() *GetHeroesHeroIDItemPopularityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get heroes hero ID item popularity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesHeroIDItemPopularityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) WithTimeout(timeout time.Duration) *GetHeroesHeroIDItemPopularityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) WithContext(ctx context.Context) *GetHeroesHeroIDItemPopularityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) WithHTTPClient(client *http.Client) *GetHeroesHeroIDItemPopularityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeroID adds the heroID to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) WithHeroID(heroID int64) *GetHeroesHeroIDItemPopularityParams {
	o.SetHeroID(heroID)
	return o
}

// SetHeroID adds the heroId to the get heroes hero ID item popularity params
func (o *GetHeroesHeroIDItemPopularityParams) SetHeroID(heroID int64) {
	o.HeroID = heroID
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeroesHeroIDItemPopularityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hero_id
	if err := r.SetPathParam("hero_id", swag.FormatInt64(o.HeroID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
