// Code generated by go-swagger; DO NOT EDIT.

package heroes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetHeroesHeroIDItemPopularityReader is a Reader for the GetHeroesHeroIDItemPopularity structure.
type GetHeroesHeroIDItemPopularityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHeroesHeroIDItemPopularityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHeroesHeroIDItemPopularityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHeroesHeroIDItemPopularityOK creates a GetHeroesHeroIDItemPopularityOK with default headers values
func NewGetHeroesHeroIDItemPopularityOK() *GetHeroesHeroIDItemPopularityOK {
	return &GetHeroesHeroIDItemPopularityOK{}
}

/* GetHeroesHeroIDItemPopularityOK describes a response with status code 200, with default header values.

Success
*/
type GetHeroesHeroIDItemPopularityOK struct {
	Payload *GetHeroesHeroIDItemPopularityOKBody
}

func (o *GetHeroesHeroIDItemPopularityOK) Error() string {
	return fmt.Sprintf("[GET /heroes/{hero_id}/itemPopularity][%d] getHeroesHeroIdItemPopularityOK  %+v", 200, o.Payload)
}
func (o *GetHeroesHeroIDItemPopularityOK) GetPayload() *GetHeroesHeroIDItemPopularityOKBody {
	return o.Payload
}

func (o *GetHeroesHeroIDItemPopularityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetHeroesHeroIDItemPopularityOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetHeroesHeroIDItemPopularityOKBody get heroes hero ID item popularity o k body
swagger:model GetHeroesHeroIDItemPopularityOKBody
*/
type GetHeroesHeroIDItemPopularityOKBody struct {

	// early game items
	EarlyGameItems *GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems `json:"early_game_items,omitempty"`

	// late game items
	LateGameItems *GetHeroesHeroIDItemPopularityOKBodyLateGameItems `json:"late_game_items,omitempty"`

	// mid game items
	MidGameItems *GetHeroesHeroIDItemPopularityOKBodyMidGameItems `json:"mid_game_items,omitempty"`

	// start game items
	StartGameItems *GetHeroesHeroIDItemPopularityOKBodyStartGameItems `json:"start_game_items,omitempty"`
}

// Validate validates this get heroes hero ID item popularity o k body
func (o *GetHeroesHeroIDItemPopularityOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEarlyGameItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLateGameItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMidGameItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStartGameItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) validateEarlyGameItems(formats strfmt.Registry) error {
	if swag.IsZero(o.EarlyGameItems) { // not required
		return nil
	}

	if o.EarlyGameItems != nil {
		if err := o.EarlyGameItems.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "early_game_items")
			}
			return err
		}
	}

	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) validateLateGameItems(formats strfmt.Registry) error {
	if swag.IsZero(o.LateGameItems) { // not required
		return nil
	}

	if o.LateGameItems != nil {
		if err := o.LateGameItems.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "late_game_items")
			}
			return err
		}
	}

	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) validateMidGameItems(formats strfmt.Registry) error {
	if swag.IsZero(o.MidGameItems) { // not required
		return nil
	}

	if o.MidGameItems != nil {
		if err := o.MidGameItems.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "mid_game_items")
			}
			return err
		}
	}

	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) validateStartGameItems(formats strfmt.Registry) error {
	if swag.IsZero(o.StartGameItems) { // not required
		return nil
	}

	if o.StartGameItems != nil {
		if err := o.StartGameItems.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "start_game_items")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get heroes hero ID item popularity o k body based on the context it is used
func (o *GetHeroesHeroIDItemPopularityOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateEarlyGameItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateLateGameItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMidGameItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateStartGameItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) contextValidateEarlyGameItems(ctx context.Context, formats strfmt.Registry) error {

	if o.EarlyGameItems != nil {
		if err := o.EarlyGameItems.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "early_game_items")
			}
			return err
		}
	}

	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) contextValidateLateGameItems(ctx context.Context, formats strfmt.Registry) error {

	if o.LateGameItems != nil {
		if err := o.LateGameItems.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "late_game_items")
			}
			return err
		}
	}

	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) contextValidateMidGameItems(ctx context.Context, formats strfmt.Registry) error {

	if o.MidGameItems != nil {
		if err := o.MidGameItems.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "mid_game_items")
			}
			return err
		}
	}

	return nil
}

func (o *GetHeroesHeroIDItemPopularityOKBody) contextValidateStartGameItems(ctx context.Context, formats strfmt.Registry) error {

	if o.StartGameItems != nil {
		if err := o.StartGameItems.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getHeroesHeroIdItemPopularityOK" + "." + "start_game_items")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBody) UnmarshalBinary(b []byte) error {
	var res GetHeroesHeroIDItemPopularityOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems Items bought in the first 10 min of the game, with cost at least 700
swagger:model GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems
*/
type GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems struct {

	// Number of item bought
	Item int64 `json:"item,omitempty"`
}

// Validate validates this get heroes hero ID item popularity o k body early game items
func (o *GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get heroes hero ID item popularity o k body early game items based on context it is used
func (o *GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems) UnmarshalBinary(b []byte) error {
	var res GetHeroesHeroIDItemPopularityOKBodyEarlyGameItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetHeroesHeroIDItemPopularityOKBodyLateGameItems Items bought at least 25 min after game started, with cost at least 4000
swagger:model GetHeroesHeroIDItemPopularityOKBodyLateGameItems
*/
type GetHeroesHeroIDItemPopularityOKBodyLateGameItems struct {

	// Number of item bought
	Item int64 `json:"item,omitempty"`
}

// Validate validates this get heroes hero ID item popularity o k body late game items
func (o *GetHeroesHeroIDItemPopularityOKBodyLateGameItems) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get heroes hero ID item popularity o k body late game items based on context it is used
func (o *GetHeroesHeroIDItemPopularityOKBodyLateGameItems) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyLateGameItems) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyLateGameItems) UnmarshalBinary(b []byte) error {
	var res GetHeroesHeroIDItemPopularityOKBodyLateGameItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetHeroesHeroIDItemPopularityOKBodyMidGameItems Items bought between 10 and 25 min of the game, with cost at least 2000
swagger:model GetHeroesHeroIDItemPopularityOKBodyMidGameItems
*/
type GetHeroesHeroIDItemPopularityOKBodyMidGameItems struct {

	// Number of item bought
	Item int64 `json:"item,omitempty"`
}

// Validate validates this get heroes hero ID item popularity o k body mid game items
func (o *GetHeroesHeroIDItemPopularityOKBodyMidGameItems) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get heroes hero ID item popularity o k body mid game items based on context it is used
func (o *GetHeroesHeroIDItemPopularityOKBodyMidGameItems) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyMidGameItems) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyMidGameItems) UnmarshalBinary(b []byte) error {
	var res GetHeroesHeroIDItemPopularityOKBodyMidGameItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetHeroesHeroIDItemPopularityOKBodyStartGameItems Items bought before game started
swagger:model GetHeroesHeroIDItemPopularityOKBodyStartGameItems
*/
type GetHeroesHeroIDItemPopularityOKBodyStartGameItems struct {

	// Number of item bought
	Item int64 `json:"item,omitempty"`
}

// Validate validates this get heroes hero ID item popularity o k body start game items
func (o *GetHeroesHeroIDItemPopularityOKBodyStartGameItems) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get heroes hero ID item popularity o k body start game items based on context it is used
func (o *GetHeroesHeroIDItemPopularityOKBodyStartGameItems) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyStartGameItems) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroesHeroIDItemPopularityOKBodyStartGameItems) UnmarshalBinary(b []byte) error {
	var res GetHeroesHeroIDItemPopularityOKBodyStartGameItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
