// Code generated by go-swagger; DO NOT EDIT.

package heroes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetHeroesHeroIDMatchesParams creates a new GetHeroesHeroIDMatchesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHeroesHeroIDMatchesParams() *GetHeroesHeroIDMatchesParams {
	return &GetHeroesHeroIDMatchesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeroesHeroIDMatchesParamsWithTimeout creates a new GetHeroesHeroIDMatchesParams object
// with the ability to set a timeout on a request.
func NewGetHeroesHeroIDMatchesParamsWithTimeout(timeout time.Duration) *GetHeroesHeroIDMatchesParams {
	return &GetHeroesHeroIDMatchesParams{
		timeout: timeout,
	}
}

// NewGetHeroesHeroIDMatchesParamsWithContext creates a new GetHeroesHeroIDMatchesParams object
// with the ability to set a context for a request.
func NewGetHeroesHeroIDMatchesParamsWithContext(ctx context.Context) *GetHeroesHeroIDMatchesParams {
	return &GetHeroesHeroIDMatchesParams{
		Context: ctx,
	}
}

// NewGetHeroesHeroIDMatchesParamsWithHTTPClient creates a new GetHeroesHeroIDMatchesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHeroesHeroIDMatchesParamsWithHTTPClient(client *http.Client) *GetHeroesHeroIDMatchesParams {
	return &GetHeroesHeroIDMatchesParams{
		HTTPClient: client,
	}
}

/* GetHeroesHeroIDMatchesParams contains all the parameters to send to the API endpoint
   for the get heroes hero ID matches operation.

   Typically these are written to a http.Request.
*/
type GetHeroesHeroIDMatchesParams struct {

	/* HeroID.

	   Hero ID
	*/
	HeroID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get heroes hero ID matches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesHeroIDMatchesParams) WithDefaults() *GetHeroesHeroIDMatchesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get heroes hero ID matches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroesHeroIDMatchesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) WithTimeout(timeout time.Duration) *GetHeroesHeroIDMatchesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) WithContext(ctx context.Context) *GetHeroesHeroIDMatchesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) WithHTTPClient(client *http.Client) *GetHeroesHeroIDMatchesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeroID adds the heroID to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) WithHeroID(heroID int64) *GetHeroesHeroIDMatchesParams {
	o.SetHeroID(heroID)
	return o
}

// SetHeroID adds the heroId to the get heroes hero ID matches params
func (o *GetHeroesHeroIDMatchesParams) SetHeroID(heroID int64) {
	o.HeroID = heroID
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeroesHeroIDMatchesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hero_id
	if err := r.SetPathParam("hero_id", swag.FormatInt64(o.HeroID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
