// Code generated by go-swagger; DO NOT EDIT.

package heroes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetHeroesHeroIDMatchesReader is a Reader for the GetHeroesHeroIDMatches structure.
type GetHeroesHeroIDMatchesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHeroesHeroIDMatchesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHeroesHeroIDMatchesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHeroesHeroIDMatchesOK creates a GetHeroesHeroIDMatchesOK with default headers values
func NewGetHeroesHeroIDMatchesOK() *GetHeroesHeroIDMatchesOK {
	return &GetHeroesHeroIDMatchesOK{}
}

/* GetHeroesHeroIDMatchesOK describes a response with status code 200, with default header values.

Success
*/
type GetHeroesHeroIDMatchesOK struct {
	Payload []*GetHeroesHeroIDMatchesOKBodyItems0
}

func (o *GetHeroesHeroIDMatchesOK) Error() string {
	return fmt.Sprintf("[GET /heroes/{hero_id}/matches][%d] getHeroesHeroIdMatchesOK  %+v", 200, o.Payload)
}
func (o *GetHeroesHeroIDMatchesOK) GetPayload() []*GetHeroesHeroIDMatchesOKBodyItems0 {
	return o.Payload
}

func (o *GetHeroesHeroIDMatchesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetHeroesHeroIDMatchesOKBodyItems0 get heroes hero ID matches o k body items0
swagger:model GetHeroesHeroIDMatchesOKBodyItems0
*/
type GetHeroesHeroIDMatchesOKBodyItems0 struct {

	// The Dire's team name
	DireName string `json:"dire_name,omitempty"`

	// Number of kills the Dire team had when the match ended
	DireScore int64 `json:"dire_score,omitempty"`

	// The Dire's team_id
	DireTeamID int64 `json:"dire_team_id,omitempty"`

	// Length of the match
	Duration int64 `json:"duration,omitempty"`

	// Name of league the match took place in
	LeagueName string `json:"league_name,omitempty"`

	// Identifier for the league the match took place in
	Leagueid int64 `json:"leagueid,omitempty"`

	// Used to identify individual matches, e.g. 3703866531
	MatchID int64 `json:"match_id,omitempty"`

	// Whether the team/player/hero was on Radiant
	Radiant bool `json:"radiant,omitempty"`

	// The Radiant's team name
	RadiantName string `json:"radiant_name,omitempty"`

	// Number of kills the Radiant team had when the match ended
	RadiantScore int64 `json:"radiant_score,omitempty"`

	// The Radiant's team_id
	RadiantTeamID int64 `json:"radiant_team_id,omitempty"`

	// Whether or not the Radiant won the match
	RadiantWin bool `json:"radiant_win,omitempty"`

	// Identifier for the series of the match
	SeriesID int64 `json:"series_id,omitempty"`

	// Type of series the match was
	SeriesType int64 `json:"series_type,omitempty"`

	// Unix timestamp of when the match began
	StartTime int64 `json:"start_time,omitempty"`
}

// Validate validates this get heroes hero ID matches o k body items0
func (o *GetHeroesHeroIDMatchesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get heroes hero ID matches o k body items0 based on context it is used
func (o *GetHeroesHeroIDMatchesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroesHeroIDMatchesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroesHeroIDMatchesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetHeroesHeroIDMatchesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
