// Code generated by go-swagger; DO NOT EDIT.

package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetSchemaReader is a Reader for the GetSchema structure.
type GetSchemaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSchemaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSchemaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSchemaOK creates a GetSchemaOK with default headers values
func NewGetSchemaOK() *GetSchemaOK {
	return &GetSchemaOK{}
}

/* GetSchemaOK describes a response with status code 200, with default header values.

Success
*/
type GetSchemaOK struct {
	Payload []*GetSchemaOKBodyItems0
}

func (o *GetSchemaOK) Error() string {
	return fmt.Sprintf("[GET /schema][%d] getSchemaOK  %+v", 200, o.Payload)
}
func (o *GetSchemaOK) GetPayload() []*GetSchemaOKBodyItems0 {
	return o.Payload
}

func (o *GetSchemaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetSchemaOKBodyItems0 get schema o k body items0
swagger:model GetSchemaOKBodyItems0
*/
type GetSchemaOKBodyItems0 struct {

	// column_name
	ColumnName string `json:"column_name,omitempty"`

	// data_type
	DataType string `json:"data_type,omitempty"`

	// table_name
	TableName string `json:"table_name,omitempty"`
}

// Validate validates this get schema o k body items0
func (o *GetSchemaOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get schema o k body items0 based on context it is used
func (o *GetSchemaOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSchemaOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSchemaOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetSchemaOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
