// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRecordsFieldParams creates a new GetRecordsFieldParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRecordsFieldParams() *GetRecordsFieldParams {
	return &GetRecordsFieldParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecordsFieldParamsWithTimeout creates a new GetRecordsFieldParams object
// with the ability to set a timeout on a request.
func NewGetRecordsFieldParamsWithTimeout(timeout time.Duration) *GetRecordsFieldParams {
	return &GetRecordsFieldParams{
		timeout: timeout,
	}
}

// NewGetRecordsFieldParamsWithContext creates a new GetRecordsFieldParams object
// with the ability to set a context for a request.
func NewGetRecordsFieldParamsWithContext(ctx context.Context) *GetRecordsFieldParams {
	return &GetRecordsFieldParams{
		Context: ctx,
	}
}

// NewGetRecordsFieldParamsWithHTTPClient creates a new GetRecordsFieldParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRecordsFieldParamsWithHTTPClient(client *http.Client) *GetRecordsFieldParams {
	return &GetRecordsFieldParams{
		HTTPClient: client,
	}
}

/* GetRecordsFieldParams contains all the parameters to send to the API endpoint
   for the get records field operation.

   Typically these are written to a http.Request.
*/
type GetRecordsFieldParams struct {

	/* Field.

	   Field name to query
	*/
	Field string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get records field params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRecordsFieldParams) WithDefaults() *GetRecordsFieldParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get records field params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRecordsFieldParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get records field params
func (o *GetRecordsFieldParams) WithTimeout(timeout time.Duration) *GetRecordsFieldParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get records field params
func (o *GetRecordsFieldParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get records field params
func (o *GetRecordsFieldParams) WithContext(ctx context.Context) *GetRecordsFieldParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get records field params
func (o *GetRecordsFieldParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get records field params
func (o *GetRecordsFieldParams) WithHTTPClient(client *http.Client) *GetRecordsFieldParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get records field params
func (o *GetRecordsFieldParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithField adds the field to the get records field params
func (o *GetRecordsFieldParams) WithField(field string) *GetRecordsFieldParams {
	o.SetField(field)
	return o
}

// SetField adds the field to the get records field params
func (o *GetRecordsFieldParams) SetField(field string) {
	o.Field = field
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecordsFieldParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param field
	if err := r.SetPathParam("field", o.Field); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
