// Code generated by go-swagger; DO NOT EDIT.

package scenarios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetScenariosItemTimingsReader is a Reader for the GetScenariosItemTimings structure.
type GetScenariosItemTimingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScenariosItemTimingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScenariosItemTimingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetScenariosItemTimingsOK creates a GetScenariosItemTimingsOK with default headers values
func NewGetScenariosItemTimingsOK() *GetScenariosItemTimingsOK {
	return &GetScenariosItemTimingsOK{}
}

/* GetScenariosItemTimingsOK describes a response with status code 200, with default header values.

Success
*/
type GetScenariosItemTimingsOK struct {
	Payload []*GetScenariosItemTimingsOKBodyItems0
}

func (o *GetScenariosItemTimingsOK) Error() string {
	return fmt.Sprintf("[GET /scenarios/itemTimings][%d] getScenariosItemTimingsOK  %+v", 200, o.Payload)
}
func (o *GetScenariosItemTimingsOK) GetPayload() []*GetScenariosItemTimingsOKBodyItems0 {
	return o.Payload
}

func (o *GetScenariosItemTimingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetScenariosItemTimingsOKBodyItems0 get scenarios item timings o k body items0
swagger:model GetScenariosItemTimingsOKBodyItems0
*/
type GetScenariosItemTimingsOKBodyItems0 struct {

	// The number of games where the hero bought this item before this time
	Games string `json:"games,omitempty"`

	// Hero ID
	HeroID int64 `json:"hero_id,omitempty"`

	// Purchased item
	Item string `json:"item,omitempty"`

	// Ingame time in seconds before the item was purchased
	Time int64 `json:"time,omitempty"`

	// The number of games won where the hero bought this item before this time
	Wins string `json:"wins,omitempty"`
}

// Validate validates this get scenarios item timings o k body items0
func (o *GetScenariosItemTimingsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get scenarios item timings o k body items0 based on context it is used
func (o *GetScenariosItemTimingsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetScenariosItemTimingsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScenariosItemTimingsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetScenariosItemTimingsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
