// Code generated by go-swagger; DO NOT EDIT.

package scenarios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetScenariosLaneRolesReader is a Reader for the GetScenariosLaneRoles structure.
type GetScenariosLaneRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScenariosLaneRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScenariosLaneRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetScenariosLaneRolesOK creates a GetScenariosLaneRolesOK with default headers values
func NewGetScenariosLaneRolesOK() *GetScenariosLaneRolesOK {
	return &GetScenariosLaneRolesOK{}
}

/* GetScenariosLaneRolesOK describes a response with status code 200, with default header values.

Success
*/
type GetScenariosLaneRolesOK struct {
	Payload []*GetScenariosLaneRolesOKBodyItems0
}

func (o *GetScenariosLaneRolesOK) Error() string {
	return fmt.Sprintf("[GET /scenarios/laneRoles][%d] getScenariosLaneRolesOK  %+v", 200, o.Payload)
}
func (o *GetScenariosLaneRolesOK) GetPayload() []*GetScenariosLaneRolesOKBodyItems0 {
	return o.Payload
}

func (o *GetScenariosLaneRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetScenariosLaneRolesOKBodyItems0 get scenarios lane roles o k body items0
swagger:model GetScenariosLaneRolesOKBodyItems0
*/
type GetScenariosLaneRolesOKBodyItems0 struct {

	// The number of games where the hero played in this lane role
	Games string `json:"games,omitempty"`

	// Hero ID
	HeroID int64 `json:"hero_id,omitempty"`

	// The hero's lane role
	LaneRole int64 `json:"lane_role,omitempty"`

	// Maximum game length in seconds
	Time int64 `json:"time,omitempty"`

	// The number of games won where the hero played in this lane role
	Wins string `json:"wins,omitempty"`
}

// Validate validates this get scenarios lane roles o k body items0
func (o *GetScenariosLaneRolesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get scenarios lane roles o k body items0 based on context it is used
func (o *GetScenariosLaneRolesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetScenariosLaneRolesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScenariosLaneRolesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetScenariosLaneRolesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
