// Code generated by go-swagger; DO NOT EDIT.

package replays

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetReplaysReader is a Reader for the GetReplays structure.
type GetReplaysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReplaysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReplaysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetReplaysOK creates a GetReplaysOK with default headers values
func NewGetReplaysOK() *GetReplaysOK {
	return &GetReplaysOK{}
}

/* GetReplaysOK describes a response with status code 200, with default header values.

Success
*/
type GetReplaysOK struct {
	Payload []*GetReplaysOKBodyItems0
}

func (o *GetReplaysOK) Error() string {
	return fmt.Sprintf("[GET /replays][%d] getReplaysOK  %+v", 200, o.Payload)
}
func (o *GetReplaysOK) GetPayload() []*GetReplaysOKBodyItems0 {
	return o.Payload
}

func (o *GetReplaysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetReplaysOKBodyItems0 get replays o k body items0
swagger:model GetReplaysOKBodyItems0
*/
type GetReplaysOKBodyItems0 struct {

	// cluster
	Cluster int64 `json:"cluster,omitempty"`

	// match_id
	MatchID int64 `json:"match_id,omitempty"`

	// replay_salt
	ReplaySalt int64 `json:"replay_salt,omitempty"`
}

// Validate validates this get replays o k body items0
func (o *GetReplaysOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get replays o k body items0 based on context it is used
func (o *GetReplaysOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetReplaysOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetReplaysOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetReplaysOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
