// Code generated by go-swagger; DO NOT EDIT.

package replays

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetReplaysParams creates a new GetReplaysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReplaysParams() *GetReplaysParams {
	return &GetReplaysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReplaysParamsWithTimeout creates a new GetReplaysParams object
// with the ability to set a timeout on a request.
func NewGetReplaysParamsWithTimeout(timeout time.Duration) *GetReplaysParams {
	return &GetReplaysParams{
		timeout: timeout,
	}
}

// NewGetReplaysParamsWithContext creates a new GetReplaysParams object
// with the ability to set a context for a request.
func NewGetReplaysParamsWithContext(ctx context.Context) *GetReplaysParams {
	return &GetReplaysParams{
		Context: ctx,
	}
}

// NewGetReplaysParamsWithHTTPClient creates a new GetReplaysParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReplaysParamsWithHTTPClient(client *http.Client) *GetReplaysParams {
	return &GetReplaysParams{
		HTTPClient: client,
	}
}

/* GetReplaysParams contains all the parameters to send to the API endpoint
   for the get replays operation.

   Typically these are written to a http.Request.
*/
type GetReplaysParams struct {

	/* MatchID.

	   Match IDs (array)
	*/
	MatchID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get replays params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReplaysParams) WithDefaults() *GetReplaysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get replays params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReplaysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get replays params
func (o *GetReplaysParams) WithTimeout(timeout time.Duration) *GetReplaysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get replays params
func (o *GetReplaysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get replays params
func (o *GetReplaysParams) WithContext(ctx context.Context) *GetReplaysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get replays params
func (o *GetReplaysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get replays params
func (o *GetReplaysParams) WithHTTPClient(client *http.Client) *GetReplaysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get replays params
func (o *GetReplaysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMatchID adds the matchID to the get replays params
func (o *GetReplaysParams) WithMatchID(matchID int64) *GetReplaysParams {
	o.SetMatchID(matchID)
	return o
}

// SetMatchID adds the matchId to the get replays params
func (o *GetReplaysParams) SetMatchID(matchID int64) {
	o.MatchID = matchID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReplaysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param match_id
	qrMatchID := o.MatchID
	qMatchID := swag.FormatInt64(qrMatchID)
	if qMatchID != "" {

		if err := r.SetQueryParam("match_id", qMatchID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
