// Code generated by go-swagger; DO NOT EDIT.

package request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostRequestMatchIDParams creates a new PostRequestMatchIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRequestMatchIDParams() *PostRequestMatchIDParams {
	return &PostRequestMatchIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRequestMatchIDParamsWithTimeout creates a new PostRequestMatchIDParams object
// with the ability to set a timeout on a request.
func NewPostRequestMatchIDParamsWithTimeout(timeout time.Duration) *PostRequestMatchIDParams {
	return &PostRequestMatchIDParams{
		timeout: timeout,
	}
}

// NewPostRequestMatchIDParamsWithContext creates a new PostRequestMatchIDParams object
// with the ability to set a context for a request.
func NewPostRequestMatchIDParamsWithContext(ctx context.Context) *PostRequestMatchIDParams {
	return &PostRequestMatchIDParams{
		Context: ctx,
	}
}

// NewPostRequestMatchIDParamsWithHTTPClient creates a new PostRequestMatchIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRequestMatchIDParamsWithHTTPClient(client *http.Client) *PostRequestMatchIDParams {
	return &PostRequestMatchIDParams{
		HTTPClient: client,
	}
}

/* PostRequestMatchIDParams contains all the parameters to send to the API endpoint
   for the post request match ID operation.

   Typically these are written to a http.Request.
*/
type PostRequestMatchIDParams struct {

	// MatchID.
	MatchID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post request match ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRequestMatchIDParams) WithDefaults() *PostRequestMatchIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post request match ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRequestMatchIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post request match ID params
func (o *PostRequestMatchIDParams) WithTimeout(timeout time.Duration) *PostRequestMatchIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post request match ID params
func (o *PostRequestMatchIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post request match ID params
func (o *PostRequestMatchIDParams) WithContext(ctx context.Context) *PostRequestMatchIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post request match ID params
func (o *PostRequestMatchIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post request match ID params
func (o *PostRequestMatchIDParams) WithHTTPClient(client *http.Client) *PostRequestMatchIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post request match ID params
func (o *PostRequestMatchIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMatchID adds the matchID to the post request match ID params
func (o *PostRequestMatchIDParams) WithMatchID(matchID int64) *PostRequestMatchIDParams {
	o.SetMatchID(matchID)
	return o
}

// SetMatchID adds the matchId to the post request match ID params
func (o *PostRequestMatchIDParams) SetMatchID(matchID int64) {
	o.MatchID = matchID
}

// WriteToRequest writes these params to a swagger request
func (o *PostRequestMatchIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param match_id
	if err := r.SetPathParam("match_id", swag.FormatInt64(o.MatchID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
