// Code generated by go-swagger; DO NOT EDIT.

package request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostRequestMatchIDReader is a Reader for the PostRequestMatchID structure.
type PostRequestMatchIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRequestMatchIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostRequestMatchIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostRequestMatchIDOK creates a PostRequestMatchIDOK with default headers values
func NewPostRequestMatchIDOK() *PostRequestMatchIDOK {
	return &PostRequestMatchIDOK{}
}

/* PostRequestMatchIDOK describes a response with status code 200, with default header values.

Success
*/
type PostRequestMatchIDOK struct {
	Payload interface{}
}

func (o *PostRequestMatchIDOK) Error() string {
	return fmt.Sprintf("[POST /request/{match_id}][%d] postRequestMatchIdOK  %+v", 200, o.Payload)
}
func (o *PostRequestMatchIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostRequestMatchIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
