// Code generated by go-swagger; DO NOT EDIT.

package request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new request API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for request API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetRequestJobID(params *GetRequestJobIDParams, opts ...ClientOption) (*GetRequestJobIDOK, error)

	PostRequestMatchID(params *PostRequestMatchIDParams, opts ...ClientOption) (*PostRequestMatchIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetRequestJobID gs e t request job Id

  Get parse request state
*/
func (a *Client) GetRequestJobID(params *GetRequestJobIDParams, opts ...ClientOption) (*GetRequestJobIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRequestJobIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetRequestJobID",
		Method:             "GET",
		PathPattern:        "/request/{jobId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetRequestJobIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRequestJobIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetRequestJobID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostRequestMatchID ps o s t request match id

  Submit a new parse request
*/
func (a *Client) PostRequestMatchID(params *PostRequestMatchIDParams, opts ...ClientOption) (*PostRequestMatchIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostRequestMatchIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostRequestMatchID",
		Method:             "POST",
		PathPattern:        "/request/{match_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostRequestMatchIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostRequestMatchIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostRequestMatchID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
