// Code generated by go-swagger; DO NOT EDIT.

package explorer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetExplorerReader is a Reader for the GetExplorer structure.
type GetExplorerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExplorerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExplorerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetExplorerOK creates a GetExplorerOK with default headers values
func NewGetExplorerOK() *GetExplorerOK {
	return &GetExplorerOK{}
}

/* GetExplorerOK describes a response with status code 200, with default header values.

Success
*/
type GetExplorerOK struct {
	Payload interface{}
}

func (o *GetExplorerOK) Error() string {
	return fmt.Sprintf("[GET /explorer][%d] getExplorerOK  %+v", 200, o.Payload)
}
func (o *GetExplorerOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetExplorerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
