// Code generated by go-swagger; DO NOT EDIT.

package public_matches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetPublicMatchesReader is a Reader for the GetPublicMatches structure.
type GetPublicMatchesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPublicMatchesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPublicMatchesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPublicMatchesOK creates a GetPublicMatchesOK with default headers values
func NewGetPublicMatchesOK() *GetPublicMatchesOK {
	return &GetPublicMatchesOK{}
}

/* GetPublicMatchesOK describes a response with status code 200, with default header values.

Success
*/
type GetPublicMatchesOK struct {
	Payload []*GetPublicMatchesOKBodyItems0
}

func (o *GetPublicMatchesOK) Error() string {
	return fmt.Sprintf("[GET /publicMatches][%d] getPublicMatchesOK  %+v", 200, o.Payload)
}
func (o *GetPublicMatchesOK) GetPayload() []*GetPublicMatchesOKBodyItems0 {
	return o.Payload
}

func (o *GetPublicMatchesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPublicMatchesOKBodyItems0 get public matches o k body items0
swagger:model GetPublicMatchesOKBodyItems0
*/
type GetPublicMatchesOKBodyItems0 struct {

	// dire_team
	DireTeam string `json:"dire_team,omitempty"`

	// Duration of the game in seconds
	Duration int64 `json:"duration,omitempty"`

	// match_id
	MatchID int64 `json:"match_id,omitempty"`

	// match_seq_num
	MatchSeqNum int64 `json:"match_seq_num,omitempty"`

	// radiant_team
	RadiantTeam string `json:"radiant_team,omitempty"`

	// Boolean indicating whether Radiant won the match
	RadiantWin bool `json:"radiant_win,omitempty"`

	// start_time
	StartTime int64 `json:"start_time,omitempty"`
}

// Validate validates this get public matches o k body items0
func (o *GetPublicMatchesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get public matches o k body items0 based on context it is used
func (o *GetPublicMatchesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPublicMatchesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPublicMatchesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetPublicMatchesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
