// Code generated by go-swagger; DO NOT EDIT.

package hero_stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetHeroStatsReader is a Reader for the GetHeroStats structure.
type GetHeroStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHeroStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHeroStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHeroStatsOK creates a GetHeroStatsOK with default headers values
func NewGetHeroStatsOK() *GetHeroStatsOK {
	return &GetHeroStatsOK{}
}

/* GetHeroStatsOK describes a response with status code 200, with default header values.

Success
*/
type GetHeroStatsOK struct {
	Payload []*GetHeroStatsOKBodyItems0
}

func (o *GetHeroStatsOK) Error() string {
	return fmt.Sprintf("[GET /heroStats][%d] getHeroStatsOK  %+v", 200, o.Payload)
}
func (o *GetHeroStatsOK) GetPayload() []*GetHeroStatsOKBodyItems0 {
	return o.Payload
}

func (o *GetHeroStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetHeroStatsOKBodyItems0 get hero stats o k body items0
swagger:model GetHeroStatsOKBodyItems0
*/
type GetHeroStatsOKBodyItems0 struct {

	// Herald picks
	Nr1Pick int64 `json:"1_pick,omitempty"`

	// Herald wins
	Nr1Win int64 `json:"1_win,omitempty"`

	// Guardian picks
	Nr2Pick int64 `json:"2_pick,omitempty"`

	// Guardian wins
	Nr2Win int64 `json:"2_win,omitempty"`

	// Crusader picks
	Nr3Pick int64 `json:"3_pick,omitempty"`

	// Crusader wins
	Nr3Win int64 `json:"3_win,omitempty"`

	// Archon picks
	Nr4Pick int64 `json:"4_pick,omitempty"`

	// Archon wins
	Nr4Win int64 `json:"4_win,omitempty"`

	// Legend picks
	Nr5Pick int64 `json:"5_pick,omitempty"`

	// Legend wins
	Nr5Win int64 `json:"5_win,omitempty"`

	// Ancient picks
	Nr6Pick int64 `json:"6_pick,omitempty"`

	// Ancient wins
	Nr6Win int64 `json:"6_win,omitempty"`

	// Divine picks
	Nr7Pick int64 `json:"7_pick,omitempty"`

	// Divine wins
	Nr7Win int64 `json:"7_win,omitempty"`

	// Immortal picks
	Nr8Pick int64 `json:"8_pick,omitempty"`

	// Immortal wins
	Nr8Win int64 `json:"8_win,omitempty"`

	// The ID value of the hero played
	HeroID int64 `json:"hero_id,omitempty"`

	// icon
	Icon string `json:"icon,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// img
	Img string `json:"img,omitempty"`

	// localized_name
	LocalizedName string `json:"localized_name,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pro_ban
	ProBan int64 `json:"pro_ban,omitempty"`

	// pro_pick
	ProPick int64 `json:"pro_pick,omitempty"`

	// pro_win
	ProWin int64 `json:"pro_win,omitempty"`

	// Picks in Turbo mode this month
	TurboPick int64 `json:"turbo_pick,omitempty"`

	// Wins in Turbo mode this month
	TurboWin int64 `json:"turbo_win,omitempty"`
}

// Validate validates this get hero stats o k body items0
func (o *GetHeroStatsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get hero stats o k body items0 based on context it is used
func (o *GetHeroStatsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHeroStatsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHeroStatsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetHeroStatsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
