// Code generated by go-swagger; DO NOT EDIT.

package hero_stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHeroStatsParams creates a new GetHeroStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHeroStatsParams() *GetHeroStatsParams {
	return &GetHeroStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeroStatsParamsWithTimeout creates a new GetHeroStatsParams object
// with the ability to set a timeout on a request.
func NewGetHeroStatsParamsWithTimeout(timeout time.Duration) *GetHeroStatsParams {
	return &GetHeroStatsParams{
		timeout: timeout,
	}
}

// NewGetHeroStatsParamsWithContext creates a new GetHeroStatsParams object
// with the ability to set a context for a request.
func NewGetHeroStatsParamsWithContext(ctx context.Context) *GetHeroStatsParams {
	return &GetHeroStatsParams{
		Context: ctx,
	}
}

// NewGetHeroStatsParamsWithHTTPClient creates a new GetHeroStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHeroStatsParamsWithHTTPClient(client *http.Client) *GetHeroStatsParams {
	return &GetHeroStatsParams{
		HTTPClient: client,
	}
}

/* GetHeroStatsParams contains all the parameters to send to the API endpoint
   for the get hero stats operation.

   Typically these are written to a http.Request.
*/
type GetHeroStatsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get hero stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroStatsParams) WithDefaults() *GetHeroStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get hero stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeroStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get hero stats params
func (o *GetHeroStatsParams) WithTimeout(timeout time.Duration) *GetHeroStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hero stats params
func (o *GetHeroStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hero stats params
func (o *GetHeroStatsParams) WithContext(ctx context.Context) *GetHeroStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hero stats params
func (o *GetHeroStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hero stats params
func (o *GetHeroStatsParams) WithHTTPClient(client *http.Client) *GetHeroStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hero stats params
func (o *GetHeroStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeroStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
