// Code generated by go-swagger; DO NOT EDIT.

package matches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetMatchesMatchIDParams creates a new GetMatchesMatchIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMatchesMatchIDParams() *GetMatchesMatchIDParams {
	return &GetMatchesMatchIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMatchesMatchIDParamsWithTimeout creates a new GetMatchesMatchIDParams object
// with the ability to set a timeout on a request.
func NewGetMatchesMatchIDParamsWithTimeout(timeout time.Duration) *GetMatchesMatchIDParams {
	return &GetMatchesMatchIDParams{
		timeout: timeout,
	}
}

// NewGetMatchesMatchIDParamsWithContext creates a new GetMatchesMatchIDParams object
// with the ability to set a context for a request.
func NewGetMatchesMatchIDParamsWithContext(ctx context.Context) *GetMatchesMatchIDParams {
	return &GetMatchesMatchIDParams{
		Context: ctx,
	}
}

// NewGetMatchesMatchIDParamsWithHTTPClient creates a new GetMatchesMatchIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMatchesMatchIDParamsWithHTTPClient(client *http.Client) *GetMatchesMatchIDParams {
	return &GetMatchesMatchIDParams{
		HTTPClient: client,
	}
}

/* GetMatchesMatchIDParams contains all the parameters to send to the API endpoint
   for the get matches match ID operation.

   Typically these are written to a http.Request.
*/
type GetMatchesMatchIDParams struct {

	// MatchID.
	MatchID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get matches match ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMatchesMatchIDParams) WithDefaults() *GetMatchesMatchIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get matches match ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMatchesMatchIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get matches match ID params
func (o *GetMatchesMatchIDParams) WithTimeout(timeout time.Duration) *GetMatchesMatchIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get matches match ID params
func (o *GetMatchesMatchIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get matches match ID params
func (o *GetMatchesMatchIDParams) WithContext(ctx context.Context) *GetMatchesMatchIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get matches match ID params
func (o *GetMatchesMatchIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get matches match ID params
func (o *GetMatchesMatchIDParams) WithHTTPClient(client *http.Client) *GetMatchesMatchIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get matches match ID params
func (o *GetMatchesMatchIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMatchID adds the matchID to the get matches match ID params
func (o *GetMatchesMatchIDParams) WithMatchID(matchID int64) *GetMatchesMatchIDParams {
	o.SetMatchID(matchID)
	return o
}

// SetMatchID adds the matchId to the get matches match ID params
func (o *GetMatchesMatchIDParams) SetMatchID(matchID int64) {
	o.MatchID = matchID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMatchesMatchIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param match_id
	if err := r.SetPathParam("match_id", swag.FormatInt64(o.MatchID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
