// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTeamsTeamIDReader is a Reader for the GetTeamsTeamID structure.
type GetTeamsTeamIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTeamsTeamIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTeamsTeamIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTeamsTeamIDOK creates a GetTeamsTeamIDOK with default headers values
func NewGetTeamsTeamIDOK() *GetTeamsTeamIDOK {
	return &GetTeamsTeamIDOK{}
}

/* GetTeamsTeamIDOK describes a response with status code 200, with default header values.

Success
*/
type GetTeamsTeamIDOK struct {
	Payload *GetTeamsTeamIDOKBody
}

func (o *GetTeamsTeamIDOK) Error() string {
	return fmt.Sprintf("[GET /teams/{team_id}][%d] getTeamsTeamIdOK  %+v", 200, o.Payload)
}
func (o *GetTeamsTeamIDOK) GetPayload() *GetTeamsTeamIDOKBody {
	return o.Payload
}

func (o *GetTeamsTeamIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTeamsTeamIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTeamsTeamIDOKBody get teams team ID o k body
swagger:model GetTeamsTeamIDOKBody
*/
type GetTeamsTeamIDOKBody struct {

	// The Unix timestamp of the last match played by this team
	LastMatchTime int64 `json:"last_match_time,omitempty"`

	// The number of losses by this team
	Losses int64 `json:"losses,omitempty"`

	// Team name, eg. 'Newbee'
	Name string `json:"name,omitempty"`

	// The Elo rating of the team
	Rating float64 `json:"rating,omitempty"`

	// The team tag/abbreviation
	Tag string `json:"tag,omitempty"`

	// Team's identifier
	TeamID int64 `json:"team_id,omitempty"`

	// The number of games won by this team
	Wins int64 `json:"wins,omitempty"`
}

// Validate validates this get teams team ID o k body
func (o *GetTeamsTeamIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get teams team ID o k body based on context it is used
func (o *GetTeamsTeamIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTeamsTeamIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTeamsTeamIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetTeamsTeamIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
