// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTeamsTeamIDParams creates a new GetTeamsTeamIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTeamsTeamIDParams() *GetTeamsTeamIDParams {
	return &GetTeamsTeamIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTeamsTeamIDParamsWithTimeout creates a new GetTeamsTeamIDParams object
// with the ability to set a timeout on a request.
func NewGetTeamsTeamIDParamsWithTimeout(timeout time.Duration) *GetTeamsTeamIDParams {
	return &GetTeamsTeamIDParams{
		timeout: timeout,
	}
}

// NewGetTeamsTeamIDParamsWithContext creates a new GetTeamsTeamIDParams object
// with the ability to set a context for a request.
func NewGetTeamsTeamIDParamsWithContext(ctx context.Context) *GetTeamsTeamIDParams {
	return &GetTeamsTeamIDParams{
		Context: ctx,
	}
}

// NewGetTeamsTeamIDParamsWithHTTPClient creates a new GetTeamsTeamIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTeamsTeamIDParamsWithHTTPClient(client *http.Client) *GetTeamsTeamIDParams {
	return &GetTeamsTeamIDParams{
		HTTPClient: client,
	}
}

/* GetTeamsTeamIDParams contains all the parameters to send to the API endpoint
   for the get teams team ID operation.

   Typically these are written to a http.Request.
*/
type GetTeamsTeamIDParams struct {

	/* TeamID.

	   Team ID
	*/
	TeamID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get teams team ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeamsTeamIDParams) WithDefaults() *GetTeamsTeamIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get teams team ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeamsTeamIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get teams team ID params
func (o *GetTeamsTeamIDParams) WithTimeout(timeout time.Duration) *GetTeamsTeamIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get teams team ID params
func (o *GetTeamsTeamIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get teams team ID params
func (o *GetTeamsTeamIDParams) WithContext(ctx context.Context) *GetTeamsTeamIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get teams team ID params
func (o *GetTeamsTeamIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get teams team ID params
func (o *GetTeamsTeamIDParams) WithHTTPClient(client *http.Client) *GetTeamsTeamIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get teams team ID params
func (o *GetTeamsTeamIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeamID adds the teamID to the get teams team ID params
func (o *GetTeamsTeamIDParams) WithTeamID(teamID int64) *GetTeamsTeamIDParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the get teams team ID params
func (o *GetTeamsTeamIDParams) SetTeamID(teamID int64) {
	o.TeamID = teamID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTeamsTeamIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param team_id
	if err := r.SetPathParam("team_id", swag.FormatInt64(o.TeamID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
