// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTeamsTeamIDHeroesReader is a Reader for the GetTeamsTeamIDHeroes structure.
type GetTeamsTeamIDHeroesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTeamsTeamIDHeroesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTeamsTeamIDHeroesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTeamsTeamIDHeroesOK creates a GetTeamsTeamIDHeroesOK with default headers values
func NewGetTeamsTeamIDHeroesOK() *GetTeamsTeamIDHeroesOK {
	return &GetTeamsTeamIDHeroesOK{}
}

/* GetTeamsTeamIDHeroesOK describes a response with status code 200, with default header values.

Success
*/
type GetTeamsTeamIDHeroesOK struct {
	Payload *GetTeamsTeamIDHeroesOKBody
}

func (o *GetTeamsTeamIDHeroesOK) Error() string {
	return fmt.Sprintf("[GET /teams/{team_id}/heroes][%d] getTeamsTeamIdHeroesOK  %+v", 200, o.Payload)
}
func (o *GetTeamsTeamIDHeroesOK) GetPayload() *GetTeamsTeamIDHeroesOKBody {
	return o.Payload
}

func (o *GetTeamsTeamIDHeroesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTeamsTeamIDHeroesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTeamsTeamIDHeroesOKBody get teams team ID heroes o k body
swagger:model GetTeamsTeamIDHeroesOKBody
*/
type GetTeamsTeamIDHeroesOKBody struct {

	// Number of games played
	GamesPlayed int64 `json:"games_played,omitempty"`

	// The hero ID
	HeroID int64 `json:"hero_id,omitempty"`

	// The hero name
	Name string `json:"name,omitempty"`

	// Number of wins
	Wins int64 `json:"wins,omitempty"`
}

// Validate validates this get teams team ID heroes o k body
func (o *GetTeamsTeamIDHeroesOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get teams team ID heroes o k body based on context it is used
func (o *GetTeamsTeamIDHeroesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTeamsTeamIDHeroesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTeamsTeamIDHeroesOKBody) UnmarshalBinary(b []byte) error {
	var res GetTeamsTeamIDHeroesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
