// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTeamsTeamIDPlayersReader is a Reader for the GetTeamsTeamIDPlayers structure.
type GetTeamsTeamIDPlayersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTeamsTeamIDPlayersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTeamsTeamIDPlayersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTeamsTeamIDPlayersOK creates a GetTeamsTeamIDPlayersOK with default headers values
func NewGetTeamsTeamIDPlayersOK() *GetTeamsTeamIDPlayersOK {
	return &GetTeamsTeamIDPlayersOK{}
}

/* GetTeamsTeamIDPlayersOK describes a response with status code 200, with default header values.

Success
*/
type GetTeamsTeamIDPlayersOK struct {
	Payload *GetTeamsTeamIDPlayersOKBody
}

func (o *GetTeamsTeamIDPlayersOK) Error() string {
	return fmt.Sprintf("[GET /teams/{team_id}/players][%d] getTeamsTeamIdPlayersOK  %+v", 200, o.Payload)
}
func (o *GetTeamsTeamIDPlayersOK) GetPayload() *GetTeamsTeamIDPlayersOKBody {
	return o.Payload
}

func (o *GetTeamsTeamIDPlayersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTeamsTeamIDPlayersOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTeamsTeamIDPlayersOKBody get teams team ID players o k body
swagger:model GetTeamsTeamIDPlayersOKBody
*/
type GetTeamsTeamIDPlayersOKBody struct {

	// The player account ID
	AccountID string `json:"account_id,omitempty"`

	// Number of games played
	GamesPlayed int64 `json:"games_played,omitempty"`

	// If this player is on the current roster
	IsCurrentTeamMember bool `json:"is_current_team_member,omitempty"`

	// The player name
	Name string `json:"name,omitempty"`

	// Number of wins
	Wins int64 `json:"wins,omitempty"`
}

// Validate validates this get teams team ID players o k body
func (o *GetTeamsTeamIDPlayersOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get teams team ID players o k body based on context it is used
func (o *GetTeamsTeamIDPlayersOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTeamsTeamIDPlayersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTeamsTeamIDPlayersOKBody) UnmarshalBinary(b []byte) error {
	var res GetTeamsTeamIDPlayersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
