// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTeamsTeamIDMatchesParams creates a new GetTeamsTeamIDMatchesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTeamsTeamIDMatchesParams() *GetTeamsTeamIDMatchesParams {
	return &GetTeamsTeamIDMatchesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTeamsTeamIDMatchesParamsWithTimeout creates a new GetTeamsTeamIDMatchesParams object
// with the ability to set a timeout on a request.
func NewGetTeamsTeamIDMatchesParamsWithTimeout(timeout time.Duration) *GetTeamsTeamIDMatchesParams {
	return &GetTeamsTeamIDMatchesParams{
		timeout: timeout,
	}
}

// NewGetTeamsTeamIDMatchesParamsWithContext creates a new GetTeamsTeamIDMatchesParams object
// with the ability to set a context for a request.
func NewGetTeamsTeamIDMatchesParamsWithContext(ctx context.Context) *GetTeamsTeamIDMatchesParams {
	return &GetTeamsTeamIDMatchesParams{
		Context: ctx,
	}
}

// NewGetTeamsTeamIDMatchesParamsWithHTTPClient creates a new GetTeamsTeamIDMatchesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTeamsTeamIDMatchesParamsWithHTTPClient(client *http.Client) *GetTeamsTeamIDMatchesParams {
	return &GetTeamsTeamIDMatchesParams{
		HTTPClient: client,
	}
}

/* GetTeamsTeamIDMatchesParams contains all the parameters to send to the API endpoint
   for the get teams team ID matches operation.

   Typically these are written to a http.Request.
*/
type GetTeamsTeamIDMatchesParams struct {

	/* TeamID.

	   Team ID
	*/
	TeamID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get teams team ID matches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeamsTeamIDMatchesParams) WithDefaults() *GetTeamsTeamIDMatchesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get teams team ID matches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeamsTeamIDMatchesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) WithTimeout(timeout time.Duration) *GetTeamsTeamIDMatchesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) WithContext(ctx context.Context) *GetTeamsTeamIDMatchesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) WithHTTPClient(client *http.Client) *GetTeamsTeamIDMatchesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeamID adds the teamID to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) WithTeamID(teamID int64) *GetTeamsTeamIDMatchesParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the get teams team ID matches params
func (o *GetTeamsTeamIDMatchesParams) SetTeamID(teamID int64) {
	o.TeamID = teamID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTeamsTeamIDMatchesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param team_id
	if err := r.SetPathParam("team_id", swag.FormatInt64(o.TeamID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
