// Code generated by go-swagger; DO NOT EDIT.

package players_by_rank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetPlayersByRankReader is a Reader for the GetPlayersByRank structure.
type GetPlayersByRankReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlayersByRankReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlayersByRankOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPlayersByRankOK creates a GetPlayersByRankOK with default headers values
func NewGetPlayersByRankOK() *GetPlayersByRankOK {
	return &GetPlayersByRankOK{}
}

/* GetPlayersByRankOK describes a response with status code 200, with default header values.

Success
*/
type GetPlayersByRankOK struct {
	Payload *GetPlayersByRankOKBody
}

func (o *GetPlayersByRankOK) Error() string {
	return fmt.Sprintf("[GET /playersByRank][%d] getPlayersByRankOK  %+v", 200, o.Payload)
}
func (o *GetPlayersByRankOK) GetPayload() *GetPlayersByRankOKBody {
	return o.Payload
}

func (o *GetPlayersByRankOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlayersByRankOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPlayersByRankOKBody get players by rank o k body
swagger:model GetPlayersByRankOKBody
*/
type GetPlayersByRankOKBody struct {

	// account_id
	AccountID float64 `json:"account_id,omitempty"`

	// Indicates if we were unable to fetch full history for this player due to privacy settings
	FhUnavailable bool `json:"fh_unavailable,omitempty"`

	// Integer indicating the rank/medal of the player
	RankTier float64 `json:"rank_tier,omitempty"`
}

// Validate validates this get players by rank o k body
func (o *GetPlayersByRankOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get players by rank o k body based on context it is used
func (o *GetPlayersByRankOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPlayersByRankOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlayersByRankOKBody) UnmarshalBinary(b []byte) error {
	var res GetPlayersByRankOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
