// Code generated by go-swagger; DO NOT EDIT.

package constants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetConstantsResourceReader is a Reader for the GetConstantsResource structure.
type GetConstantsResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConstantsResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConstantsResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetConstantsResourceOK creates a GetConstantsResourceOK with default headers values
func NewGetConstantsResourceOK() *GetConstantsResourceOK {
	return &GetConstantsResourceOK{}
}

/* GetConstantsResourceOK describes a response with status code 200, with default header values.

Success
*/
type GetConstantsResourceOK struct {
	Payload []interface{}
}

func (o *GetConstantsResourceOK) Error() string {
	return fmt.Sprintf("[GET /constants/{resource}][%d] getConstantsResourceOK  %+v", 200, o.Payload)
}
func (o *GetConstantsResourceOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetConstantsResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
