// Code generated by go-swagger; DO NOT EDIT.

package constants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConstantsResourceParams creates a new GetConstantsResourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetConstantsResourceParams() *GetConstantsResourceParams {
	return &GetConstantsResourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetConstantsResourceParamsWithTimeout creates a new GetConstantsResourceParams object
// with the ability to set a timeout on a request.
func NewGetConstantsResourceParamsWithTimeout(timeout time.Duration) *GetConstantsResourceParams {
	return &GetConstantsResourceParams{
		timeout: timeout,
	}
}

// NewGetConstantsResourceParamsWithContext creates a new GetConstantsResourceParams object
// with the ability to set a context for a request.
func NewGetConstantsResourceParamsWithContext(ctx context.Context) *GetConstantsResourceParams {
	return &GetConstantsResourceParams{
		Context: ctx,
	}
}

// NewGetConstantsResourceParamsWithHTTPClient creates a new GetConstantsResourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetConstantsResourceParamsWithHTTPClient(client *http.Client) *GetConstantsResourceParams {
	return &GetConstantsResourceParams{
		HTTPClient: client,
	}
}

/* GetConstantsResourceParams contains all the parameters to send to the API endpoint
   for the get constants resource operation.

   Typically these are written to a http.Request.
*/
type GetConstantsResourceParams struct {

	/* Resource.

	   Resource name e.g. `heroes`. [List of resources](https://github.com/odota/dotaconstants/tree/master/build)
	*/
	Resource string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get constants resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConstantsResourceParams) WithDefaults() *GetConstantsResourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get constants resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConstantsResourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get constants resource params
func (o *GetConstantsResourceParams) WithTimeout(timeout time.Duration) *GetConstantsResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get constants resource params
func (o *GetConstantsResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get constants resource params
func (o *GetConstantsResourceParams) WithContext(ctx context.Context) *GetConstantsResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get constants resource params
func (o *GetConstantsResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get constants resource params
func (o *GetConstantsResourceParams) WithHTTPClient(client *http.Client) *GetConstantsResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get constants resource params
func (o *GetConstantsResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResource adds the resource to the get constants resource params
func (o *GetConstantsResourceParams) WithResource(resource string) *GetConstantsResourceParams {
	o.SetResource(resource)
	return o
}

// SetResource adds the resource to the get constants resource params
func (o *GetConstantsResourceParams) SetResource(resource string) {
	o.Resource = resource
}

// WriteToRequest writes these params to a swagger request
func (o *GetConstantsResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resource
	if err := r.SetPathParam("resource", o.Resource); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
